command-usage: '&cUsage: /tpa <player>'
player-not-found: '&cPlayer not found!'
tpa-request: '&e%player% &fwants to teleport you!'
dont-have-request: '&cYou don''t have any requests!'
already-requested: '&c%player% has already a waiting request!'
accept-button-text: '&a&l[ACCEPT]'
accept-button-hover: '&aAccept the request!'
deny-button-text: '&c&l[DENY]'
deny-button-hover: '&cDeny the request!'
tpa-title: '&6Teleported'
tpa-subtitle: '&fX: %f Y: %f Z: %f'
tpdeny: '&4%player% has rejected your teleport request!'
only-players: '&cThis command is executable by players only!'